### ISSUE TITLE
research: 研究 access token 和 ID token 的区别

### ISSUE THREAD

**Issue by gao-sun** [logto-io/middleware#10]

**Comment by wangsijie** [comment]
https://www.notion.so/logto/ID-Token-vs-Access-Token-f30b4e82281c41329aa1cad1c55b5739

总结和明确几个点：

1. 请求的时候只带上access_token
2. IDToken保存在client后不再传出(极少数场景如吊销等除外)
3. access_token对应于传统意义上的user_token，而IDToken则可以理解为basic user info，“缓存”在client
4. IDToken的签名，是client校验，用于信任签发者

**Comment by xiaoyijun** [comment]
调研了一些需求和回顾了Slack中的讨论，发现一些知识点有点出入
https://www.notion.so/logto/ID-Token-vs-Access-Token-f30b4e82281c41329aa1cad1c55b5739
例会可以讨论一下
